__git_complete g __git_main
__git_complete ga _git_add
__git_complete gai _git_add
__git_complete gap _git_add
__git_complete gau _git_add
__git_complete gb _git_branch
__git_complete gba _git_branch
__git_complete gbd _git_branch
__git_complete gbr _git_branch
__git_complete gc _git_commit
__git_complete gca _git_commit
__git_complete gcf _git_cfg
__git_complete gcl _git_clean
__git_complete gco _git_checkout
__git_complete gcob _git_checkout
__git_complete gcop _git_checkout
__git_complete gcp _git_cherry-pick
__git_complete gd _git_diff
__git_complete gdc _git_diff
__git_complete gds _git_diff
__git_complete gf _git_fetch
__git_complete gh _git_help
__git_complete gl _git_log
__git_complete gm _git_merge
__git_complete gma _git_merge
__git_complete gmv _git_mv
__git_complete gp _git_push
__git_complete gpa _git_push
__git_complete gpl _git_pull
__git_complete gpu _git_push
__git_complete gr _git_reset
__git_complete grb _git_rebase
__git_complete grba _git_rebase
__git_complete grbc _git_rebase
__git_complete grbi _git_rebase
__git_complete grbs _git_rebase
__git_complete grh _git_reset
__git_complete grm _git_rm
__git_complete grmt _git_remote
__git_complete gsh _git_show
__git_complete gsmu _git_submodule
__git_complete gst _git_stash
__git_complete gstc _git_stash
__git_complete gstd _git_stash
__git_complete gstl _git_stash
__git_complete gstp _git_stash
__git_complete gsts _git_stash

